def generate_strategy_fallback(
    monthly_income: float,
    monthly_expenses: float,
    outstanding_amount: float,
    loan_type: str,
    overdue_months: int,
    interest_rate: float,
    lender_name: str,
) -> str:
    surplus = monthly_income - monthly_expenses
    repayment_capacity = surplus * 0.6

    if surplus <= 0:
        affordability = "extremely limited"
        plan = "debt restructuring or professional debt counseling"
    elif repayment_capacity < outstanding_amount * 0.02:
        affordability = "very limited"
        plan = "extended repayment plan over 24-36 months"
    elif repayment_capacity < outstanding_amount * 0.05:
        affordability = "moderate"
        plan = "accelerated repayment plan over 12-18 months"
    else:
        affordability = "reasonable"
        plan = "lump-sum settlement negotiation"

    # Settlement percentage recommendation
    if overdue_months > 12:
        pct = "50-60%"
    elif overdue_months > 6:
        pct = "60-70%"
    elif overdue_months > 3:
        pct = "70-80%"
    else:
        pct = "80-90%"

    return (
        f"=== FINRELIEF AI — NEGOTIATION STRATEGY (Rule-Based Analysis) ===\n\n"
        f"LOAN OVERVIEW\n"
        f"  Loan Type: {loan_type.replace('_', ' ').title()}\n"
        f"  Lender: {lender_name}\n"
        f"  Outstanding: ₹{outstanding_amount:,.2f}\n"
        f"  Interest Rate: {interest_rate}%\n"
        f"  Overdue: {overdue_months} month(s)\n\n"
        f"FINANCIAL SNAPSHOT\n"
        f"  Monthly Income: ₹{monthly_income:,.2f}\n"
        f"  Monthly Expenses: ₹{monthly_expenses:,.2f}\n"
        f"  Monthly Surplus: ₹{surplus:,.2f}\n"
        f"  Repayment Capacity (60% of surplus): ₹{repayment_capacity:,.2f}\n"
        f"  Affordability Assessment: {affordability.title()}\n\n"
        f"RECOMMENDED STRATEGY\n"
        f"  1. Settlement Range: Aim for {pct} of outstanding balance.\n"
        f"  2. Approach: Initiate contact with {lender_name}'s collections department.\n"
        f"  3. Recommended Plan: {plan.title()}.\n"
        f"  4. Key Argument: Highlight {overdue_months} months of non-payment and willingness to resolve.\n"
        f"  5. Fallback: If settlement is rejected, propose a structured EMI plan at ₹{repayment_capacity:,.2f}/month.\n\n"
        f"TIMELINE\n"
        f"  • Week 1: Send formal settlement request letter.\n"
        f"  • Week 2-3: Follow up and negotiate terms.\n"
        f"  • Week 4: Finalize agreement and arrange payment.\n\n"
        f"NOTE: This recommendation was generated by the rule-based engine. "
        f"For AI-powered personalized strategies, configure your Gemini API key.\n"
    )


def generate_letter_fallback(
    borrower_name: str,
    lender_name: str,
    loan_type: str,
    outstanding_amount: float,
    proposed_settlement_amount: float,
    overdue_months: int,
    reason: str,
) -> str:
    settlement_pct = round((proposed_settlement_amount / outstanding_amount) * 100, 1) if outstanding_amount > 0 else 0

    return (
        f"Date: [Current Date]\n\n"
        f"To,\n"
        f"The Collections Manager\n"
        f"{lender_name}\n\n"
        f"Subject: Request for One-Time Settlement of {loan_type.replace('_', ' ').title()} Loan Account\n\n"
        f"Respected Sir/Madam,\n\n"
        f"I, {borrower_name}, am writing to formally request a one-time settlement for my "
        f"{loan_type.replace('_', ' ')} loan account with your institution.\n\n"
        f"Account Details:\n"
        f"  - Loan Type: {loan_type.replace('_', ' ').title()}\n"
        f"  - Outstanding Amount: ₹{outstanding_amount:,.2f}\n"
        f"  - Months Overdue: {overdue_months}\n\n"
        f"Due to {reason}, I have been unable to maintain regular payments for the past "
        f"{overdue_months} month(s). Despite my best efforts, my current financial situation "
        f"does not allow me to repay the full outstanding amount.\n\n"
        f"Settlement Proposal:\n"
        f"  I propose a one-time settlement of ₹{proposed_settlement_amount:,.2f}, "
        f"which represents {settlement_pct}% of the outstanding balance. This amount reflects "
        f"my maximum repayment capacity given my current circumstances.\n\n"
        f"I sincerely request your kind consideration of this proposal. I am committed to "
        f"resolving this matter amicably and would appreciate a written confirmation of the "
        f"settlement terms, including:\n"
        f"  1. The agreed settlement amount.\n"
        f"  2. Confirmation that no further claims will be made.\n"
        f"  3. Timeline for updating credit bureau records.\n\n"
        f"I am available for further discussion at your convenience.\n\n"
        f"Thanking you,\n"
        f"{borrower_name}\n\n"
        f"---\n"
        f"NOTE: This letter was generated by the rule-based engine. "
        f"For AI-powered personalized letters, configure your Gemini API key.\n"
    )


def chat_fallback(
    message: str,
    monthly_income: float = None,
    monthly_expenses: float = None,
    total_outstanding: float = None,
) -> str:
    msg_lower = message.lower()

    # Context-aware responses
    context_parts = []
    if monthly_income is not None and monthly_expenses is not None:
        surplus = monthly_income - monthly_expenses
        context_parts.append(
            f"Based on your financial data (income: ₹{monthly_income:,.2f}, "
            f"expenses: ₹{monthly_expenses:,.2f}, surplus: ₹{surplus:,.2f})"
        )
    if total_outstanding is not None:
        context_parts.append(f"with total outstanding debt of ₹{total_outstanding:,.2f}")

    context = ", ".join(context_parts) + ":" if context_parts else ""

    if any(word in msg_lower for word in ["settle", "settlement", "negotiate"]):
        return (
            f"FinRelief AI Counselor (Rule-Based):\n\n"
            f"{context}\n\n"
            f"Settlement negotiation typically involves these steps:\n"
            f"1. Assess your total debt and identify accounts that may accept settlements.\n"
            f"2. Contact lenders' collections departments directly.\n"
            f"3. Start negotiations at 40-50% of the outstanding amount.\n"
            f"4. Always get settlement agreements in writing before making payment.\n"
            f"5. Settled accounts may impact your credit score for 2-7 years.\n\n"
            f"Use our Settlement Prediction tool for loan-specific recommendations.\n\n"
            f"NOTE: For personalized AI-powered advice, configure your Gemini API key."
        )
    elif any(word in msg_lower for word in ["budget", "save", "saving", "expense"]):
        return (
            f"FinRelief AI Counselor (Rule-Based):\n\n"
            f"{context}\n\n"
            f"Key budgeting strategies for debt recovery:\n"
            f"1. Follow the 50/30/20 rule: 50% needs, 30% wants, 20% debt repayment.\n"
            f"2. Track every expense for 30 days to identify reduction opportunities.\n"
            f"3. Eliminate non-essential subscriptions and services.\n"
            f"4. Build an emergency fund of at least 1 month's expenses.\n"
            f"5. Allocate at least 60% of your surplus to debt repayment.\n\n"
            f"Use our Financial Health calculator for detailed analysis.\n\n"
            f"NOTE: For personalized AI-powered advice, configure your Gemini API key."
        )
    elif any(word in msg_lower for word in ["credit", "score", "cibil"]):
        return (
            f"FinRelief AI Counselor (Rule-Based):\n\n"
            f"{context}\n\n"
            f"Tips to rebuild your credit score:\n"
            f"1. Pay all current EMIs on time — payment history is the biggest factor.\n"
            f"2. Reduce credit utilization below 30% of your total credit limit.\n"
            f"3. Avoid applying for new credit while recovering.\n"
            f"4. Dispute any inaccuracies on your credit report.\n"
            f"5. Consider a secured credit card to rebuild history.\n"
            f"6. Settled accounts stay on your report for 7 years.\n\n"
            f"NOTE: For personalized AI-powered advice, configure your Gemini API key."
        )
    else:
        return (
            f"FinRelief AI Counselor (Rule-Based):\n\n"
            f"{context}\n\n"
            f"I can help you with:\n"
            f"• Settlement negotiations — ask about settling your loans.\n"
            f"• Budgeting strategies — ask about saving money or reducing expenses.\n"
            f"• Credit score recovery — ask about improving your credit score.\n"
            f"• Debt repayment plans — use our Financial Health and Settlement tools.\n\n"
            f"Try asking a more specific question about one of these topics.\n\n"
            f"NOTE: For full conversational AI support, configure your Gemini API key."
        )
